# Generated by Django 4.0.3 on 2022-03-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=9)),
                ('fecha_nacimiento', models.CharField(default='1/1/2000', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_nacimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_residencia', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_sangre', models.CharField(choices=[('', 'None'), ('A+', 'A1'), ('A-', 'A2'), ('B+', 'B1'), ('B-', 'B2'), ('AB+', 'Ab1'), ('AB-', 'Ab2'), ('O+', 'O1'), ('O-', 'O2')], default='', max_length=10)),
                ('tipo_idenfiticacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admisiones.tipoidentificacion')),
            ],
        ),
    ]
